from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import time
from selenium.webdriver.common.by import By

#***************************
#Bug detected:
    #Tweeting from the profile page enter inf loop [CANT TEST IT]
    #Navigation bar enters inf loop with prfile page [CANT TEST IT]
#***************************

def Buttons(Driver):
    #liking / Retweeting / Commenting sectionj from home page
    #home page

    HomeComment = Driver.find_element(by=By.XPATH,value='(//android.widget.ImageView[@content-desc="0"])[1]')
    HomeComment.click()
    time.sleep(2)
    Reply = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View[1]/android.view.View/android.widget.EditText')
    Reply.click()
    time.sleep(2)
    quote1="Replying to the tweet"
    Reply.send_keys(quote1)
    time.sleep(2)
    ReplyButton = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Reply"]')
    ReplyButton.click()
    time.sleep(2)
    HomeComment.click()
    Reply = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View[1]/android.view.View/android.widget.EditText')
    Reply.click()
    time.sleep(2)
    Reply.send_keys(quote1)
    CancelButton1 = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Cancel"]')
    CancelButton1.click()
    time.sleep(2)
    Retweet = Driver.find_element(by=By.XPATH,value='(//android.widget.ImageView[@content-desc="5"])[1]')
    Retweet.click()
    time.sleep(2)
    Retweet.click()
    time.sleep(2)
    Like = Driver.find_element(by=By.XPATH,value='(//android.widget.ImageView[@content-desc="0"])[2]')
    Like.click()
    time.sleep(2)
    Like.click()
    time.sleep(2)

    HomePageSetting = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[2]')
    HomePageSetting.click()
    time.sleep(3)

    AccountInfo = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Account information See your account information like your phone number and email address."]/android.widget.Button')
    time.sleep(3)
    AccountInfo.click()
    time.sleep(3)
    #editting the username
    Username= Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Username Nada"]')
    Username.click()
    time.sleep(3)
    ChangeUsername = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.EditText')
    ChangeUsername.click()
    time.sleep(3)
    quote2="abod"
    ChangeUsername.send_keys(quote2)
    Done = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Done"]')
    Done.click()
    time.sleep(3)
    AccountInfo.click()
    time.sleep(3)
    Username.click()
    time.sleep(3)
    ChangeUsername.click()
    time.sleep(3)
    ChangeUsername.send_keys(quote2)
    time.sleep()
    Cancel2 = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Cancel"]')
    Cancel2.click()
    time.sleep(3)
    #phone
    Phone = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Phone 123"]')
    Phone.click()
    time.sleep(3)
    # Cancel3 = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Cancel"]')
    # Cancel3 = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Cancel"]')
    Cancel2.click()
    time.sleep(3)
    #email
    AccountInfo.click()
    time.sleep(3)
    Email = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Email nadatarek2710@gmail.com"]')
    Email.click()
    time.sleep(3)
    Cancel2.click()
    time.sleep(3)

    #logout *********************************************

    LogOut = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Log out"]')
    LogOut.click()
    time.sleep(3)
    ##Login test re login to the same account
    LoginLink = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Log in"]')
    LoginLink.click()
    time.sleep(3)
    Email2 = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText')
    Email2.click()
    time.sleep(3)
    email = "user1@gmail.com"
    password = "password"
    Email2.send_keys(email)
    next = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Next"]')
    next.click()
    time.sleep(3)
    Password2 = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText')
    Password2.click()
    time.sleep(3)
    Password2.send_keys(password)
    time.sleep(3)
    next.click()
    time.sleep(3)


    HomePageSetting.click()
    time.sleep(3)
    AccountInfo.click()
    time.sleep(3)
    Back = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Back"]')
    Back.click()
    time.sleep(3)

    #Change password

    ChangePassword = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Change your password Change your password at any time."]/android.widget.Button')
    ChangePassword.click()
    time.sleep(3)
    current = "password"
    new = "newpassword"
    CurrentPass=Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.EditText[1]')
    CurrentPass.click()
    time.sleep(3)
    CurrentPass.semd_keys(current)
    eye = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.EditText[1]/android.widget.Button')
    eye.click()
    time.sleep(3)
    eye.click()
    NewPassword = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.EditText[2]')
    NewPassword.click()
    time.sleep(3)
    NewPassword.send_keys(new)
    time.sleep(3)
    eye.click()
    time.sleep(3)
    eye.click()
    ConfirmPass = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.widget.EditText[3]')
    ConfirmPass.click()
    time.sleep(3)
    ConfirmPass.send_keys(new)
    time.sleep(3)
    eye.click()
    time.sleep(3)
    eye.click()
    Done = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Done"]')
    Done.click()
    time.sleep(3)
    Cancel2.click()
    time.sleep(3)

    Audience = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Audience Manage what information you allow other people on twitter to see."]/android.widget.Button')
    Audience.click()
    time.sleep(3)
    Protect = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Protect your Tweets"]/android.widget.Switch')
    Protect.click()
    time.sleep(3)
    Protect.click()
    time.sleep(3)

    Back = Driver.find_element(by=By.XPATH, value='//android.widget.Button[@content-desc="Back"]')
    # Back.click()
    # time.sleep(3)
    Back.click()
    time.sleep(3)
    NavBar = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[1]')
    NavBar.click()
    time.sleep(3)

    Logout = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Logout"]')
    Logout.click()
    time.sleep(3)
    ##Login test re login to the same account
    LoginLink = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Log in"]')
    LoginLink.click()
    time.sleep(3)
    Email2 = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText')
    Email2.click()
    time.sleep(3)
    email = "user1@gmail.com"
    password = "password"
    Email2.send_keys(email)
    next = Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="Next"]')
    next.click()
    time.sleep(3)
    Password2 = Driver.find_element(by=By.XPATH,value='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText')
    Password2.click()
    time.sleep(3)
    Password2.send_keys(password)
    time.sleep(3)
    next.click()
    time.sleep(3)



    Profile = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Profile"]')
    Profile.click()
    time.sleep(3)

    TweeTsAndReplies = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Tweets & replies Tab 2 of 4"]')
    TweeTsAndReplies.click()
    time.sleep(3)
    Media =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Media Tab 3 of 4"]')
    Like =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Likes Tab 4 of 4"]')
    Tweets =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Tweets Tab 1 of 4"]')
    Media.click()
    time.sleep(3)
    Like.click()
    time.sleep(3)
    Tweets.click()
    time.sleep(3)
    followersList =  Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="0 followers"]')
    followeringList =  Driver.find_element(by=By.XPATH,value='//android.widget.Button[@content-desc="0 following"]')
    followersList.click()
    time.sleep(3)
    followingtab =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Following Tab 2 of 2"]')
    followertab =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Followers Tab 1 of 2"]')
    followingtab.click()
    time.sleep(3)
    followertab.click()
    time.sleep(3)
    Back.click()
    time.sleep(3)
    followeringList.click()
    time.sleep(3)
    followertab.click()
    time.sleep(3)
    followingtab.click()
    time.sleep(3)
    Back.click()
    #home buttons
    Homebutton =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="timeline Tab 1 of 4"]')
    SearchButton =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="explore Tab 2 of 4"]')
    NotificationButton =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="notifications Tab 3 of 4"]')
    Messages =  Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="messages Tab 4 of 4"]')
    All = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="All Tab 1 of 2"]')
    Mentioned = Driver.find_element(by=By.XPATH,value='//android.view.View[@content-desc="Mentions Tab 2 of 2"]')
    SearchButton.click()
    time.sleep(3)
    NotificationButton.click()
    time.sleep(3)
    Mentioned.click()
    time.sleep(3)
    All.click()
    time.sleep(3)
    Messages.click()
    time.sleep(3)
    Homebutton.click()
    time.sleep(3)